name: Docker Workflow

on:
  push:
    branches:
      - main

jobs:
  docker:
    name: Docker Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: true
          region: eu-west-2

      - name: Build Docker Image
        run: |
          docker build -t ecsproject-repo .

      - name: Run Trivy Vulnerability Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ecsproject-repo:latest
          format: table
          ignore-unfixed: true
          severity: HIGH,CRITICAL

      - name: Tag Docker Image
        run: |
          docker tag ecsproject-repo:latest 156041431760.dkr.ecr.eu-west-2.amazonaws.com/ecsproject-repo:latest

      - name: Push Docker Image to ECR
        run: |
          docker push 156041431760.dkr.ecr.eu-west-2.amazonaws.com/ecsproject-repo:latest
