name: Terraform Apply

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  terraform-apply:
    name: Apply Terraform Changes
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-west-2
      TF_LOG: WARN

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0 

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Init
      run: terraform -chdir=terraform init

    - name: Terraform Plan
      id: plan
      run: terraform -chdir=terraform plan -out=tfplan
      env:
        TF_VAR_certificate_arn: ${{ secrets.CERTIFICATE_ARN }}

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform -chdir=terraform apply -auto-approve tfplan
      env:
        TF_VAR_certificate_arn: ${{ secrets.CERTIFICATE_ARN }}
